# default: &default
#   adapter: postgis
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: surfviva_full_stack_rails_development

# test:
#   <<: *default
#   database: surfviva_full_stack_rails_test

# production:
#   url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
#   # as we're using Puma, it's threads per process that the pool needs to match as each process gets
#   # it's own pool of threads. So 3 puma processes, 5 threads each just needs the pool to be 5 threads
#   # for total concurrent connections for DB being 15.
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

defaults : &defaults
  # password: somepassword
  # user: root
  # host: localhost
  migration_files_path: src/pulse/db/migrations # this is the default location for all migrations
  adapter: postgres
  encoding: unicode # might not work with jennifer?
  pool: 5 # might not work with jennifer?

development:
  db: pulse_server_development
  <<: *defaults

test:
  db: pulse_server_test
  <<: *defaults

# production:
#   <<: *default
#   db: pulse_server_production

