# default: &default
#   adapter: postgis
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: surfviva_full_stack_rails_development

# test:
#   <<: *default
#   database: surfviva_full_stack_rails_test

# production:
#   url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
#   # as we're using Puma, it's threads per process that the pool needs to match as each process gets
#   # it's own pool of threads. So 3 puma processes, 5 threads each just needs the pool to be 5 threads
#   # for total concurrent connections for DB being 15.
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

defaults : &defaults
  host: localhost
  adapter: postgres
  user: root
  password: somepassword
  migration_files_path: src/pulse/db/migrations # this is the default location for all migrations

development:
  db: blog_development
  <<: *defaults

test:
  db: blog_test
  <<: *defaults

